---
title: "How to Use the Preferable_Airline_One_Way Function"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to Use the Preferable_Airline_One_Way Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(FlyPrice)
```

Preferable_Airline_One_Way returns the data type and the most cost-effective plane tickets ranging from the cheapest to the most expensive based on matching inputs. Here's how it works:

```{r}
setwd("/Users/loannguyen/Documents/R files/LIS 4370 – R programming/FlyPrice") # This is my directory.
# Replace my directory with yours. Make sure the working directory is set correctly

library(dplyr)
library(data.table)
library(stringr)
library(tidyr)
library(sloop)

Preferable_Airline_One_Way <- function(data, SRC, DST, date, PAX, airline) {
  data <- read.csv(data)
  data2 <- data[which(data$Source == SRC &
                        data$Destination == DST &
                        data$Date_of_Journey == date &
                        data$Airline == airline),]
  data2 <- data2 %>% mutate(Total = Price * PAX)
  data2 <- setorder(data2, Price, Total)
  rownames(data2) <- NULL
  return(c(otype(data2), View(data2)))
}

Preferable_Airline_One_Way("Flightist.csv", "Banglore", "New Delhi", "03/03/2019", 2, "Vistara Premium economy")
```
